# -*- coding: utf-8 -*-
"""python ml.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14qkFEFpJk1jZZphBL_wHHCN07KT5CbEE
"""

import pandas as pd

import numpy  as np

import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.model_selection import train_test_split

df=pd.read_csv("/content/sample_data/heart.csv")

df.head()

df.describe()

df.info()

df.describe()

df.shape

from sklearn.preprocessing import LabelEncoder

label=LabelEncoder()

label

df['age']

label.fit_transform(df['age'])

df['age'] = label.fit_transform(df['age'])

df.drop(60, axis=0)

df.columns

X = df.drop('target',axis=1)

X

y=df['target']

y

df['target'].value_counts().plot(kind='bar')

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train.shape

X_test.shape

X.shape

y_train.shape

y_test.shape

y.shape

from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X_train,y_train)

logreg.fit(X_train,y_train)

logreg.score(X_test,y_test)*100

from sklearn.tree import DecisionTreeClassifier

from sklearn.neighbors import KNeighborsClassifier

from sklearn.naive_bayes import BernoulliNB

from sklearn.svm import SVC

from sklearn.naive_bayes import GaussianNB

dtree = DecisionTreeClassifier()

knn = KNeighborsClassifier()

svm = SVC()

nb_b = BernoulliNB

from sklearn.naive_bayes import GaussianNB, BernoulliNB

# Instantiate BernoulliNB and GaussianNB
nb_b = BernoulliNB()
nb_g = GaussianNB()

models = [dtree, knn, svm, nb_b, nb_g]

models

import time

for x in models:
    print(x)
    time.sleep(1)

for X in models:
    X.fit(X_train,y_train)
    scr = X.score(X_test,y_test)
    print(X,end="==")
    print(scr)
    time.sleep(1)

